version: 2
ethernets:
  interface0:
    match:
      name: ens192
    dhcp4: false
    addresses:
      - CIIP/CINETMASK
    gateway4: CIGATEWAY
    nameservers:
      search: [CIDNSSEARCH]
      addresses: [CIDNS]
