version: 2
ethernets:
  interface0:
    match:
      name: ens192
    dhcp4: false
    addresses:
      - CIIP/24
    gateway4: 10.0.0.1
    nameservers:
      search: [skelnet.lan]
      addresses: [10.0.0.53]
